import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1512, height: 982 } })
await page.goto('http://localhost:5173')
await page.waitForTimeout(500)
const buttons = await page.$$('button')
await buttons[1].click()
await page.waitForTimeout(300)
const card = await page.$('text=HUITZILOPOCHTLI')
await card.hover()
await page.waitForTimeout(200)
await page.screenshot({ path: '/tmp/hover_check3.png', clip: { x: 60, y: 160, width: 450, height: 400 } })
await browser.close()
